-- создание таблицы
CREATE TABLE events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    cost            INTEGER,
    duration        INTEGER,
    event_date      TIMESTAMP(6),
    event_status    VARCHAR(255),
    location_id     BIGINT,
    max_places      INTEGER,
    name            VARCHAR(255),
    occupied_places INTEGER,
    owner_id        BIGINT
);

-- создание индексов
CREATE INDEX IF NOT EXISTS idx_events_cost ON events (cost);
CREATE INDEX IF NOT EXISTS idx_events_duration ON events (duration);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_events_event_status ON events (event_status);
CREATE INDEX IF NOT EXISTS idx_events_location_id ON events (location_id);
CREATE INDEX IF NOT EXISTS idx_events_max_places ON events (max_places);
CREATE INDEX IF NOT EXISTS idx_events_name ON events (name);
CREATE INDEX IF NOT EXISTS idx_events_occupied_places ON events (occupied_places);
CREATE INDEX IF NOT EXISTS idx_events_owner_id ON events (owner_id);

-- Удаление индексов, если они существуют
DROP INDEX IF EXISTS idx_events_cost;
DROP INDEX IF EXISTS idx_events_duration;
DROP INDEX IF EXISTS idx_events_event_date;
DROP INDEX IF EXISTS idx_events_event_status;
DROP INDEX IF EXISTS idx_events_location_id;
DROP INDEX IF EXISTS idx_events_max_places;
DROP INDEX IF EXISTS idx_events_name;
DROP INDEX IF EXISTS idx_events_occupied_places;
DROP INDEX IF EXISTS idx_events_owner_id;

-- Вывести список всех индексов
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'events';
